#!/usr/bin/env bash
#  Redirection

REDIRECT="\\\trewrite ^/redirect_me https://x.com/Un_PajaroLibre permanent;"

sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "30i $REDIRECT" /etc/nginx/sites-available/default
sudo service nginx restart
