#!/usr/bin/env bash
# Install Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

echo "
frontend web-front
	bind *:80
	mode http
	default_backend web-backend

backend web-backend
	balance roundrobin
	server 508788-web-01 ubuntu@34.205.65.152:80 check
	server 508788-web-02 ubuntu@18.204.5.46:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
