#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and
#+terminates itself when receiving a SIGQUIT or SIGTERM signal

sudo touch /var/run/holbertonscript.pid
function hate() {
	echo "I hate the kill command"
	sudo rm /var/run/myscript.pid
	exit
}
trap 'hate' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'sudo rm /var/run/myscript.pid' SIGQUIT
fname="/var/run/myscript.pid"
echo $$ >>$fname
while true; do
	echo "To infinity and beyond"
	sleep 2
done
