#!/usr/bin/env bash
#script that displays To infinity and beyond indefinitely.
#In between each iteration of the loop, add a sleep 2
trap 'echo "I am invincible!!!"' 15
i=1
while [ $i -gt 0 ]; do
	echo "To infinity and beyond"
	sleep 2
done

