#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=1
while [ $i -le 20 ]; do
	case $i in
		4)
			echo "$i"
			echo "bad luck China"
			;;
		9)
			echo "$i"
			echo "good luck Japan"
			;;
		17)
			echo "$i"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
	esac
	i=$((i+1))
done
