#!/usr/bin/env bash
# Run Nginx as Nginx

"""sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/enginx/sites-available/default

pkill -1 apache2

sudo -u nginx service nginx restart
"""

chmod ugo+wrx /etc/apache2/ports.conf /etc/nginx/nginx.conf
sed -i 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill -1 apache2
sudo -u nginx service nginx restart
